### ISSUE TITLE
User need access to the sshd executable

### ISSUE THREAD

**Issue by Pamplemousse** [elnappo/ansible-role-secure-openssh-server#2]
#### Main issue

Took me a while to understand that the validations where failing because `sshd` was not in my user's PATH.
Therefore, I think it might be useful to add a check to the `pre.yml` file to verify that.
##### For debian users

`sshd` being located in `/usr/sbin`, ansible user will need sudo capabilities.
Adding a [become instruction](https://docs.ansible.com/ansible/become.html) solves the problem, example:

```
roles:
  - { role: elnappoo.secure-openssh-server,
      become: yes }
```

**Comment by elnappo** [comment]
I'm not sure if adding a test for this is a good solution. This role installs a package, updates a config file, adds ufw rules and restarts a service. All of this is clearly only possible as root. So setting `remote_user: root` or adding `become: yes` should be obligatory. I'm not aware of any ansible best practices for this.
How do you handle this?
