### ISSUE TITLE
ssh_permit_root_login: no fails

### ISSUE THREAD

**Issue by imjustmatthew** [elnappo/ansible-role-secure-openssh-server#5]
When setting:
```
  vars:
    - ssh_permit_root_login: no
```

The following error occurs:
`failed: [XXX.XXX.XXX.XXX] => (item={u'regexp': u'^PermitRootLogin ', u'line': u'PermitRootLogin False'}) => {"failed": true, "item": {"line": "PermitRootLogin False", "regexp": "^PermitRootLogin "}, "msg": "failed to validate: rc:255 error:/tmp/tmpW9eey5 line 28: unsupported option \"False\".\r\n"}`

It appears ansible's yaml syntax reads "no" as falsy and stores the value False. This can be worked around by using:
```
  vars:
    - ssh_permit_root_login: "no"
```

The simplest way forward might be to just document this in defaults/main.yml where the values for ssh_permit_root_login are already documented. I suspect the value "yes" (without quotes) will similarly be considered truthy and converted to True by ansible.

**Comment by elnappo** [comment]
Thank you for reporting this issue! I fixt it with 8fc978c. I also added a note in the README.
